<h1>Create</h1>
<form method='post' action='<?= $block->getUrl('helloworld/index/save')  ?>'>
    <div class="form-group">
        <label for="title">Name</label>
        <input type="text" class="form-control" id="title" placeholder="Enter a title" name="name">
    </div>

    <div class="form-group">
        <label for="description">Content</label>
        <input type="text" class="form-control" id="description" placeholder="Enter a description" name="content">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
